In [53]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [54]:
data=pd.read_csv("../data/amazon_alexa.tsv",sep='\t')
data.head()

,rating,date,variation,verified_reviews,feedback
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1
4,5,31-Jul-18,Charcoal Fabric,Music,1

In [55]:
column_names=data.columns.values
column_names

array(['rating', 'date', 'variation', 'verified_reviews', 'feedback'],
      dtype=object)

In [65]:
data.shape

(3149, 5)

In [ ]:
# checking for null values
data.isna().sum()

rating              0
date                0
variation           0
verified_reviews    0
feedback            0
dtype: int64

In [57]:
data[data["verified_reviews"].isna()==True]

     rating       date variation verified_reviews  feedback
473       2  29-Jun-18     White              NaN         0

In [ ]:
# removed null values
data=data.dropna()
data.isnull().sum()

rating              0
date                0
variation           0
verified_reviews    0
feedback            0
dtype: int64

In [63]:
print("The dataset shape after removing null values is",data.shape)

The dataset shape after removing null values is (3149, 5)

In [66]:
#creating a new column that contains the length of the string in the verified reviews column
data["length"]=data["verified_reviews"].apply(len)
data.head()

,rating,date,variation,verified_reviews,feedback,length
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1,13
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1,9
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1,195
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1,172
4,5,31-Jul-18,Charcoal Fabric,Music,1,5

In [ ]:
#checking if the values in length column is accurate
print(f"'verified_review' column value:{data.iloc[9]["verified_reviews"]}")
print(f"Length of the review:{len(data.iloc[9]["verified_reviews"])}")
print(f"'length' column value:{data.iloc[9]["length"]}")

'verified_review' column value:Love it! I’ve listened to songs I haven’t heard since childhood! I get the news, weather, information! It’s great!
Length of the review:114
'length' column value:114